name: Manage Winget Packages

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'add'
        type: choice
        options:
        - add
        - update
        - delete
      package_id:
        description: 'Package ID (e.g., MyCompany.MyApp)'
        required: true
        type: string
      package_version:
        description: 'Package version'
        required: true
        type: string
      manifest_path:
        description: 'Path to manifest file'
        required: false
        type: string

jobs:
  manage-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Add Package
      if: inputs.action == 'add'
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-functions-key: ${{ secrets.FUNCTION_HOST_KEY }}" \
          -d @${{ inputs.manifest_path }} \
          "https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/PackageManifestPost"

    - name: Update Package
      if: inputs.action == 'update'
      run: |
        curl -X PUT \
          -H "Content-Type: application/json" \
          -H "x-functions-key: ${{ secrets.FUNCTION_HOST_KEY }}" \
          -d @${{ inputs.manifest_path }} \
          "https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/PackageManifestPut"

    - name: Delete Package
      if: inputs.action == 'delete'
      run: |
        curl -X DELETE \
          -H "x-functions-key: ${{ secrets.FUNCTION_HOST_KEY }}" \
          "https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/PackageManifestDelete?packageId=${{ inputs.package_id }}&version=${{ inputs.package_version }}" 