name: Update Authorized Packages List

on:
  workflow_dispatch:

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
      - name: Get this repository
        uses: actions/checkout@v4

      - name: Set cache date
        id: set_date
        run: echo "CACHE_DATE=$(date +%F)" >> $GITHUB_OUTPUT

      - name: Daily cache
        id: cache
        uses: actions/cache@v4
        with:
          path: winget-pkgs
          key: winget-pkgs-${{ steps.set_date.outputs.CACHE_DATE }}
          
      - name: Get winget-pkgs repository
        if: ${{ !steps.cache.outputs.cache-hit }}
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/winget-pkgs'
          path: 'winget-pkgs'

      - name: Create output directory
        shell: pwsh
        run: New-Item -Path './Output/' -ItemType 'Directory' -Force

      - name: Run update script
        shell: pwsh
        run: |
          $params = @{
            IdListPath = './OnlineList/AuthorizedPackagesId.json'
            SearchPath = './winget-pkgs/manifests'
            OutputPath = './Output/'
          }
          . ./OnlineList/Scripts/UpdateAuthorizedPackages.ps1 @params

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: AuthorizedPackagesInfo
          path: './Output/AuthorizedPackagesInfo.json'