name: Update Authorized Packages List

on:
  workflow_dispatch:

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
      - name: Get this repository
        uses: actions/checkout@v4

      - name: Set cache date
        id: set_date
        run: echo "CACHE_DATE=$(date +%F)" >> $GITHUB_OUTPUT

      - name: Daily cache
        id: cache
        uses: actions/cache@v4
        with:
          path: winget-pkgs
          key: winget-pkgs-${{ steps.set_date.outputs.CACHE_DATE }}
          
      - name: Get winget-pkgs repository
        if: ${{ !steps.cache.outputs.cache-hit }}
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/winget-pkgs'
          path: 'winget-pkgs'

      - run: gci winget-pkgs
        shell: pwsh
      - run: gci winget-pkgs/manifests
        shell: pwsh
      - run: gci winget-pkgs/manifests/M
        shell: pwsh
      - run: gci winget-pkgs/manifests/M/Mozilla
        shell: pwsh

      - name: Run PowerShell script
        shell: pwsh
        run: |
          $params = @{
            IdListPath = './OnlineList/AuthorizedPackagesId.json'
            SearchPath = './winget-pkgs/manifests'
            OutputPath = './Output/AuthorizedPackages.yaml'
          }
          . ./OnlineList/Scripts/UpdateAuthorizedPackages.ps1 @params
